title: PESTA - Project Task Manager
description: Sistema de gerenciamento de tarefas do projeto PESTA
theme: jekyll-theme-cayman

# Configurações
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugins
plugins:
  - jekyll-relative-links

# Navegação
show_downloads: false

# GitHub
github:
  repository_url: https://github.com/BMoreiraRibeiro/PESTA
